---
- name: Add Webtatic repo
  yum:
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    state: present

- name: Install PHP
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - php70w
    - php70w-dom
    - php70w-mbstring
    - php70w-gd
    - php70w-pdo
    - php70w-json
    - php70w-xml
    - php70w-zip
    - php70w-curl
    - php70w-mcrypt
    - php70w-pear
    - php70w-mysql
    - php70w-fpm

- name: Drop in PHPinfo for debug
  file:
    src: phpinfo.php
    dest: /var/www/html/phpinfo.php
  notify: restart httpd

- name: PHP Installed Starting
  service:
    name: php-fpm
    state: started
    enabled: yes
